name: GBP dependencies analysis

on:
  workflow_call:

jobs:
  generate_dependencies:
    name: Generating Dependencies
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ORGA_GH_TOKEN }}
        path: src
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install catkin
    # WORK IN PROGRESS
    - name: catkin
      run: |
        for p in `catkin_topological_order --only-names`; do \
          echo "$p:"; catkin_topological_order --only-names \
            | grep -B1000 "^$p\$" | grep -v "^$p\$" | sed 's/^/  - /'; \
        done
